[package]
name = "litefs-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fcntl = { path = "../../fcntl-rs", version = "0.1.0" }
libc = "0.2.148"
