# fly.toml app configuration file generated for slow-server on 2023-09-06T19:35:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "caje"
primary_region = "ewr"

[build]

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[mounts]
source = "caje_data"
destination = "/data"

[env]
DATABASE_PATH = "/litefs/caje.db"
